from .baseobject import BaseObject
from ..utils import JsonTemplate, Snowflake

UserTemplate: JsonTemplate = ...

class User(BaseObject[Snowflake]):
    @property
    def mention(self) -> str: ...
    @property
    def username(self) -> str: ...
    @property
    def discriminator(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def bot(self) -> bool: ...


